todo/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('todo_show/', views.todo_show, name='todo_show'),
    path('todo_update/<int:id>/', views.todo_update, name="todo_update"),
    path('todo_post/', views.todo_post, name='todo_post'),
    path('todo_delete/<int:id>/', views.todo_delete,  name='todo_delete')
]

todotracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include(('todo.urls', 'todo'), namespace='todo'))
]

todo/models.py
from django.db import models

# Create your models here.

todo/forms.py
from django import forms


class TodoForm(forms.Form):
    topic = forms.CharField(max_length=100)
    descrption = forms.CharField(max_length=100)

todo/views.py
from pydoc_data import topics
from django.shortcuts import render
from django.http import HttpResponse
from .forms import TodoForm
from django.shortcuts import render, redirect, get_object_or_404
import random
# Create your views here.

todos_array = []
selected_id = 0


class Todo():
    def __init__(self, id,  topic, description):
        self.id = id
        self.topic = topic
        self.description = description

    def change_todo(self, topic, description):
        self.topic = topic
        self.description = description


todos_array.append(Todo(1, 'work',  'learn python Django'))
todos_array.append(Todo(2, 'play', 'play fifa 22'))


def todo_show(request):
    return render(request, 'pages/todo_show.html', {'todos_array': todos_array})


def todo_post(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            topic = form.cleaned_data['topic']
            descrption = form.cleaned_data['descrption']
            todos_array.append(
                Todo(random.randint(0, 100000), topic, descrption))
            return redirect('/todo/todo_show/')

    form = TodoForm()
    return render(request, 'pages/todo_post.html', {'form': form})


def todo_delete(request, id):
    if request.method == 'POST':
        for item in todos_array:
            print(request)
            if item.id == id:
                todos_array.remove(item)
                return redirect('/todo/todo_show/')
    return render(request, 'pages/delete_confirm.html', {})


def todo_update(request, id):
    if request.method == 'POST':
        for index, item in enumerate(todos_array):
            if item.id == id:
                form = TodoForm(request.POST)
                if form.is_valid():
                    topic = form.cleaned_data['topic']
                    descrption = form.cleaned_data['descrption']
                    todos_array[index] = Todo(item.id, topic, descrption)
                    return redirect('/todo/todo_show/')

    filtered = list(filter(lambda a: a.id == id, todos_array))
    selected_topic = filtered[0].topic
    selected_description = filtered[0].description
    form = TodoForm(
        {'topic': selected_topic, 'descrption': selected_description})
    return render(request, 'pages/todo_update.html', {'form': form})

todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <title> Todo App {% block title %}{% endblock %}</title>
  </head>
  <body>
    <!-- NavBar -->
    {% include 'partials/_navbar.html' %}
    <div class="container">
      <div class="row">
        <div class="col-md-6 m-auto">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

todo/templates/delete.html
        {% extends 'base.html' %} 
          {% block content %}          
          <div class="container">
            <form  action='.'style="display: grid;  grid-template-columns: (1 , 1fr)" method="post">
              {% csrf_token %}
              <h1>Do you want to delete the todo</h1>
              <input style="margin-top: 1rem;" class="btn btn-primary" type="submit" value="Yes" />
              <a href="/todo/showTodo"> Cancel </a>
            </form>
          </div>
          {% endblock %}

todo/templates/pages/addTodo.html
        {% extends 'base.html' %} 
          {% block content %}          
          <div class="container">
            <form  style="display: grid;  grid-template-columns: (1 , 1fr)" method="post">{% csrf_token %}
              {{ form }}
              <input style="margin-top: 1rem;" class="btn btn-primary" type="submit" value="Submit" />
            </form>
          </div>
          {% endblock %}

todo/templates/pages/deleteConfirm.html
        {% extends 'base.html' %} 
          {% block content %}          
          <div class="container">
            <form  action='.'style="display: grid;  grid-template-columns: (1 , 1fr)" method="post">
              {% csrf_token %}
              <h1>Do you want to delete the todo</h1>
              <input style="margin-top: 1rem;" class="btn btn-primary" type="submit" value="Yes" />
              <a href="/todo/showTodo"> Cancel </a>
            </form>
          </div>
          {% endblock %}

todo/templates/pages/delete_confirm.html
        {% extends 'base.html' %} 
          {% block content %}          
          <div class="container">
            <form  action='.'style="display: grid;  grid-template-columns: (1 , 1fr)" method="post">
              {% csrf_token %}
              <h1>Do you want to delete the todo</h1>
              <input style="margin-top: 1rem;" class="btn btn-primary" type="submit" value="Yes" />
              <a href="/todo/showTodo"> Cancel </a>
            </form>
          </div>
          {% endblock %}

todo/templates/pages/todo_post.html
        {% extends 'base.html' %} 
          {% block content %}          
          <div class="container">
            <form  style="display: grid;  grid-template-columns: (1 , 1fr)" method="post">{% csrf_token %}
              {{ form }}
              <input style="margin-top: 1rem;" class="btn btn-primary" type="submit" value="Submit" />
            </form>
          </div>
          {% endblock %}

todo/templates/pages/todo_show.html
{% extends 'base.html' %} 
{% block content %}          
  <div class="container">
      <h1> My Todo List!</h1>
  <ol class="list-group list-group-numbered">
    {% for todo in todos_array %}
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <div class="fw-bold">Topic: {{ todo.topic }}</div>
        Description: {{ todo.description }}
      </div>
      <div>
        <a 
            href="{% url "todo:todo_delete" todo.id %}"
            type="button" class="btn btn-danger rounded-pill">X</a>
          <a 
            href="{% url "todo:todo_update" todo.id %}"
            type="button" class="btn btn-success rounded-pill">Edit </a>
      </div>
    </li>
    {% endfor %}  
  </ol>
  {% endblock %}
  </div>

todo/templates/pages/todo_update.html
        {% extends 'base.html' %} 
          {% block content %}          
          <div class="container">
            <form  style="display: grid;  grid-template-columns: (1 , 1fr)" method="post">{% csrf_token %}
              {{ form }}
              <input style="margin-top: 1rem;" class="btn btn-primary" type="submit" value="Submit" />
            </form>
          </div>
          {% endblock %}

todo/templates/pages/todos.html
{% extends 'base.html' %} 
{% block content %}          
  <div class="container">
      <h1> My Todo List!</h1>
  <ol class="list-group list-group-numbered">
    {% for todo in todos_array %}
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <div class="fw-bold">Topic: {{ todo.topic }}</div>
        Description: {{ todo.description }}
      </div>
      <div>
        <a 
            href="{% url "todo:todo_delete" todo.id %}"
            type="button" class="btn btn-danger rounded-pill">X</a>
          <a 
            href="{% url "todo:todo_update" todo.id %}"
            type="button" class="btn btn-success rounded-pill">Edit </a>
      </div>
    </li>
    {% endfor %}  
  </ol>
  {% endblock %}
  </div>

todo/templates/pages/updateTodo.html
        {% extends 'base.html' %} 
          {% block content %}          
          <div class="container">
            <form  style="display: grid;  grid-template-columns: (1 , 1fr)" method="post">{% csrf_token %}
              {{ form }}
              <input style="margin-top: 1rem;" class="btn btn-primary" type="submit" value="Submit" />
            </form>
          </div>
          {% endblock %}

todo/templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Todo App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div style="margin-left:auto" class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="/todo/todo_post">Add Todo</a>
        <a class="nav-link" href="/todo/todo_show/">Show Todo</a>        
      </div>
    </div>
  </div>
</nav>

todo/templates/todos.html
{% extends 'base.html' %} 
{% block content %}          
  <div class="container">
      <h1> My Todo List!</h1>
  <ol class="list-group list-group-numbered">
    {% for todo in todos_array %}
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <div class="fw-bold">Topic: {{ todo.topic }}</div>
        Description: {{ todo.description }}
      </div>
      <a 
      href="{% url "todo:todo_delete" todo.id %}"
       type="button" class="btn btn-danger rounded-pill">X</a>
    </li>
          <!-- href='/todo/todoDelete/1/delete' -->
    {% endfor %}  
  </ol>
  {% endblock %}
  </div>